import { describe, expect, it } from 'vitest';
import { readFileSync } from 'node:fs';
import { join } from 'node:path';

const root = process.cwd();
const read = (path: string) => readFileSync(join(root, path), 'utf8');
const adminEvidencePanel = read('apps/web/src/features/admin/AdminBotRuntimeEvidencePanel.tsx');

function sourceForFunction(src: string, name: string): string {
  const start = src.indexOf(`export async function ${name}`);
  expect(start).toBeGreaterThanOrEqual(0);
  const next = src.indexOf('\n// ----', start + 1);
  return src.slice(start, next === -1 ? undefined : next);
}

describe('admin user bot detail guardrails', () => {
  it('loads user bot detail from safe tables without joining sealed exchange secrets', () => {
    const queries = read('apps/web/src/features/admin/queries.ts');
    const loaderModule = read('apps/web/src/features/admin/user-bot-detail-loader.ts');
    const loader = sourceForFunction(loaderModule, 'loadAdminUserBotDetailFromDb');

    expect(queries).toContain('loadAdminUserBotDetailFromDb(db, userId)');
    expect(loader).toContain('schema.entitlements');
    expect(loader).toContain('schema.botInstances');
    expect(loader).toContain('schema.botConfigs');
    expect(loader).toContain('schema.botConfigs.config');
    expect(loader).toContain('schema.botMetricSnapshots');
    expect(loader).toContain('schema.botPositionSnapshots');
    expect(loader).toContain('schema.botTradeImports');
    expect(loader).toContain('schema.integrationHealthChecks');
    expect(loader).toContain('schema.exchangeAccounts');
    expect(loader).toContain('schema.botProviderAccounts');
    expect(loader).toContain('getPublishedBotGlobalConfig');
    expect(loader).toContain('publishedAdminSystemDefault');
    expect(loader).toContain('resolveAdminBotConfigSummary');
    expect(loaderModule).toContain('safeAdminResolvedConfig');
    expect(loaderModule).toContain('adminResolvedConfigSchemaFor(productCode).safeParse');
    expect(loaderModule).toContain('BOT_CONFIG_SOURCE_KEY');
    expect(loaderModule).toContain('__wtcBotConfigSource');
    expect(loader).toContain('schema.users');
    expect(loader).toContain('schema.userRoles');
    expect(loader).not.toContain('exchangeApiKeySecrets');
    expect(loader).not.toContain('passwordHash');
    expect(loader).not.toContain('schema.botTradeImports.rawJson');
    expect(loader).toContain('schema.botMetricSnapshots.rawJson');
    expect(loaderModule).toContain('legacyClosedTradeSourceProofFromMetricRaw');
    expect(loaderModule).toContain('legacyClosedTradeSourceProofSummaryFromRaw');
    expect(loaderModule).toContain('CURRENT_LEGACY_CLOSED_TRADE_SOURCE_PROOF');
    expect(loaderModule).toContain('legacyClosedTradeSourceProofSummary');
    expect(loaderModule).toContain('summarizeLegacyClosedTradeSourceProof');
    expect(loaderModule).toContain("'global_preflight'");
    expect(loader).toContain('const closedTradeSourceProof = productCode ===');
    expect(loader).toContain('closedTradeSourceProof,');
    expect(loader).not.toContain('schema.botConfigVersions');
    expect(loaderModule).toContain('warningsFromDetail');
    expect(loaderModule).toContain('knownWarningsForProduct');
    expect(loader).toContain('healthByProduct');
    expect(loader).toContain('activeProvidersByInstance');
    expect(loader).toContain('.filter(([, rows]) => rows.length === 1)');
    expect(loader).toContain('activeProviderByInstance.get(row.botInstanceId)');
    expect(loader).toContain('ADMIN_BOT_RUNTIME_TARGETS');
    expect(loader).toContain('runtimeHealthSummary');
    expect(loader).toContain('runtimeHealth,');
    expect(loader).toContain('warningSummary: adminUserWarningSummary');
    expect(loader).not.toContain('loadBotReadModelForUser');
    expect(loader).not.toContain('loadBotReadModel(');
    expect(loader).toContain('LEGACY_PROVIDER_SCOPE_WARNING');
    expect(loader).toContain('liveControlDisabled: true');
    expect(loader).toContain('configSummary: resolveAdminBotConfigSummary');
    expect(loader).toContain('positions: stats.positions');
    expect(loader).toContain('trades: stats.trades');
    expect(loader).toContain('equityCurve: stats.equityCurve');
    expect(loaderModule).toContain('providerScoped: productCode ===');
    expect(loaderModule).toContain('No provider pub_id, raw config, secrets, or live-apply credential included');
    expect(loaderModule).not.toContain('live-apply token');
  });

  it('keeps the admin page read-only, RBAC-gated, and honest about Legacy provider scope', () => {
    const page = read('apps/web/src/app/admin/users/[userId]/bots/page.tsx');

    expect(page).toContain('requireUser');
    expect(page).toContain('assertAdmin');
    expect(page).toContain('loadAdminUserBotDetail');
    expect(page).toContain('LIVE CONTROL: DISABLED');
    expect(page).toContain('user settings: read-only');
    expect(page).toContain('provider mappings: read-only');
    expect(page).toContain('settings: {configSourceShort(bot)}');
    expect(page).toContain('user save: {userSaveLabel(bot)}');
    expect(page).toContain('MetricCard label="User ID" value={detail.user.id}');
    expect(page).toContain('hasScopedStatisticsEvidence(bot)');
    expect(page).toContain('provider account mapped');
    expect(page).toContain('provider account pending');
    expect(page).toContain('Resolved WTC settings');
    expect(page).toContain('Bot drilldown overview');
    expect(page).toContain('Selected-user statistics command center');
    expect(page).toContain('selectedUserCommandRows');
    expect(page).toContain('Statistics depth');
    expect(page).toContain('Admin boundary');
    expect(page).toContain('Settings mirror');
    expect(page).toContain('Selected-user read-only drilldown');
    expect(page).toContain('overviewRuntimeScope(bot)');
    expect(page).toContain('runtimeHealthLabel(bot)');
    expect(page).toContain('runtime: {runtimeHealthLabel(bot)}');
    expect(page).toContain('overviewWarningLabel(bot)');
    expect(page).toContain('overviewStatsLabel(bot)');
    expect(page).toContain('Jump to bot card');
    expect(page).toContain('id={botAnchor(bot)}');
    expect(page).toContain('BotOperationMapPanel');
    expect(page).toContain('Admin operation map');
    expect(page).toContain('BotLaunchReadinessPanel');
    expect(page).toContain('function adminLaunchReadinessItems(bot: AdminUserBotSummary): BotReadinessItem[]');
    expect(page).toContain('Admin launch readiness mirror');
    expect(page).toContain('Admin can inspect ${bot.productName} readiness');
    expect(page).toContain('connectionPillLabel="no live probe"');
    expect(page).toContain('showDisabledControl={false}');
    expect(page).toContain('function adminWorkerHeartbeatReadinessStatus(bot: AdminUserBotSummary): BotReadinessItem[\'status\']');
    expect(page).toContain('Aggregate worker precheck');
    expect(page).toContain('No aggregate worker row');
    expect(page).toContain('bot.workerContinuity.note');
    expect(page).toContain('freshness} aggregate');
    expect(page).toContain('not selected-user proof');
    expect(page).toContain('if (!hasScopedStatisticsEvidence(bot)) return \'attention\';');
    expect(page).toContain('Provider mapping pending');
    expect(page).toContain('No key linked');
    expect(page).toContain('Admin start/apply/stop disabled');
    expect(page).toContain('This page does not start, stop, apply config, run exchange/provider tests, edit user settings, or touch positions.');
    expect(page).toContain('AdminBotRuntimeEvidencePanel');
    expect(page).toContain('Selected-user evidence ladder');
    expect(page).toContain('userBotEvidenceMetrics(bot)');
    expect(page).toContain('userBotEvidenceRows(bot)');
    expect(page).toContain('audience="admin"');
    expect(page).toContain('framed={false}');
    expect(page).toContain('Selected-user inspection only');
    expect(page).toContain('sourceDetail');
    expect(page).toContain('Config source');
    expect(page).toContain('Resolved symbols');
    expect(page).toContain('default override');
    expect(page).toContain('user selected default');
    expect(page).toContain('System provider mappings');
    expect(page).toContain('Provider account mapping');
    expect(page).toContain('Provider account not mapped');
    expect(page).toContain('separate audited provider-mapping workflow');
    expect(page).toContain('Open positions');
    expect(page).toContain('Recent trades');
    expect(page).toContain('Equity snapshots');
    expect(page).toContain('Stats scope');
    expect(page).toContain('Canonical warning summary');
    expect(page).toContain('warningScopeLabel(bot)');
    expect(page).toContain('source: {bot.warningSummary.source}');
    expect(page).toContain('Read-only provider mapping evidence');
    expect(page).toContain('does not create, disable, or edit mappings, saved settings, exchange keys, live bot config');
    expect(page).toContain('Secret material is not loaded');
    expect(page).not.toContain('Defaults are not shown');
    expect(page).not.toContain('adminMapLegacyProviderAccountAction');
    expect(page).not.toContain('adminDisableLegacyProviderAccountAction');
    expect(page).not.toContain('Map Legacy pub_id');
    expect(page).not.toContain('CsrfField');
    expect(page).not.toContain('type="submit"');
    expect(page).not.toContain('saveBotConfigAction');
    expect(page).not.toContain('selectSystemDefaultBotConfig');
    expect(page).not.toContain('adminSaveBotGlobalConfigAction');
    expect(page).not.toContain('startBot');
    expect(page).not.toContain('stopBot');
    expect(page).not.toContain('applyConfig');
    expect(page).not.toContain('test connection');
  });

  it('renders shared admin runtime evidence without live-control or secret semantics', () => {
    const fleetPage = read('apps/web/src/app/admin/bots/page.tsx');
    const userPage = read('apps/web/src/app/admin/users/[userId]/bots/page.tsx');

    expect(adminEvidencePanel).toContain('export function AdminBotRuntimeEvidencePanel');
    expect(adminEvidencePanel).toContain('Read-only admin evidence');
    expect(adminEvidencePanel).toContain('Admin visibility is diagnostic only');
    expect(adminEvidencePanel).toContain('User-owned settings, provider mappings, credentials');
    expect(adminEvidencePanel).toContain('framed = true');
    expect(fleetPage).toContain('Admin fleet evidence ladder');
    expect(fleetPage).toContain('fleetEvidenceMetrics');
    expect(fleetPage).toContain('fleetEvidenceRows');
    expect(fleetPage).toContain('Fleet evidence separates persisted worker health');
    expect(fleetPage).toContain('User ID {mappedUser.userId}');
    expect(fleetPage).toContain('Latest Tortila metric');
    expect(fleetPage).toContain('Latest Legacy pub_id');
    expect(fleetPage).toContain('Fleet health row');
    expect(fleetPage).toContain('Tortila owner snapshots');
    expect(fleetPage).toContain('Legacy pub_id scope');
    expect(fleetPage).toContain('Admin boundary');
    expect(userPage).toContain('Selected-user evidence ladder');
    expect(userPage).toContain('Admin launch readiness mirror');
    expect(userPage).toContain('showDisabledControl={false}');
    expect(userPage).toContain('framed={false}');
    expect(userPage).toContain('Entitlement gate');
    expect(userPage).toContain('WTC settings source');
    expect(userPage).toContain('Runtime scope');
    expect(userPage).toContain('Runtime health');
    expect(userPage).toContain('User-scoped statistics');
    expect(userPage).toContain('a metric row is not the only possible proof');
    expect(fleetPage).not.toContain("from '@/features/bots/BotRuntimeEvidencePanel'");
    expect(fleetPage).not.toContain('<BotRuntimeEvidencePanel');
    expect(userPage).not.toContain("from '@/features/bots/BotRuntimeEvidencePanel'");
    expect(userPage).not.toContain('<BotRuntimeEvidencePanel');
    for (const source of [adminEvidencePanel, fleetPage, userPage]) {
      expect(source).not.toContain('getBotAdapter');
      expect(source).not.toContain('exchangeApiKeySecrets');
      expect(source).not.toContain('rawJson');
      expect(source).not.toContain('vault.open');
      expect(source).not.toContain('apiSecret');
      expect(source).not.toContain('apiKey');
      expect(source).not.toContain('sealed');
      expect(source).not.toContain('Connection verified');
      expect(source).not.toContain('startBot');
      expect(source).not.toContain('stopBot');
      expect(source).not.toContain('applyConfig');
      expect(source).not.toContain('type="submit"');
    }
  });

  it('renders a selected-user bot drilldown overview from safe DTO fields only', () => {
    const page = read('apps/web/src/app/admin/users/[userId]/bots/page.tsx');

    expect(page).toContain('function botAnchor(bot: AdminUserBotSummary): string');
    expect(page).toContain('return `bot-${bot.productCode}`');
    expect(page).toContain('Bot drilldown overview');
    expect(page).toContain('Selected-user statistics command center');
    expect(page).toContain('Admin launch readiness mirror');
    expect(page).toContain('adminConnectionReadinessItem(bot)');
    expect(page).toContain('adminWorkerHeartbeatReadinessStatus(bot)');
    expect(page).toContain('adminRuntimeReadinessStatus(bot)');
    expect(page).toContain('adminStatisticsReadinessStatus(bot)');
    expect(page).toContain('bot.workerContinuity.state !== \'ok\'');
    expect(page).toContain('user evidence present; aggregate worker pending');
    expect(page).toContain('Access open');
    expect(page).toContain('Scoped statistics');
    expect(page).toContain('Runtime attention');
    expect(page).toContain('Worker attention');
    expect(page).toContain('workerAttentionCount(detail.bots)');
    expect(page).toContain('botEvidenceCount(bot)');
    expect(page).toContain('provider mapping read-only');
    expect(page).toContain("target='worker' aggregate");
    expect(page).toContain('no live probe on render');
    expect(page).toContain('Selected-user read-only drilldown');
    expect(page).toContain('This page does not edit user settings, provider mappings, exchange keys, live bot config, or open positions.');
    expect(page).toContain('<th>Bot</th><th>Access</th><th>Settings source</th><th>Runtime scope</th><th>Warnings</th><th>Latest stats</th><th>Drilldown</th>');
    expect(page).toContain('bot.configSummary?.sourceLabel');
    expect(page).toContain('Legacy pub_id ${bot.providerAccount.providerAccountId}');
    expect(page).toContain('Legacy pub_id pending');
    expect(page).toContain('Journal import gate');
    expect(page).toContain('tortilaJournalImportGate');
    expect(page).toContain('journal evidence present');
    expect(page).toContain('persisted user-instance journal rows');
    expect(page).toContain('No /api/marks live call is made by this admin view');
    expect(page).toContain('keep journal worker monitoring');
    expect(page).toContain('positionMarkLabel');
    expect(page).toContain('positionUnrealizedPnlLabel');
    expect(page).toContain('metricUnrealizedPnlLabel');
    expect(page).toContain('<MetricCard label="Unrealized PnL" value={metricUnrealizedPnlLabel(bot)} />');
    expect(page).toContain("bot.productCode === 'tortila_bot') return 'N/A'");
    expect(page).toContain('Source-proof gate');
    expect(page).toContain('source proof blocked');
    expect(page).toContain('provide source-proof artifact');
    expect(page).toContain('Legacy closed-trade source proof is evaluated before importer work');
    expect(page).toContain('sourceProofSourceLabel');
    expect(page).toContain('global preflight');
    expect(page).toContain('sourceProofStatusLabel');
    expect(page).toContain('sourceProofMissingSummary');
    expect(page).toContain('none reported - not an all-clear');
    expect(page).toContain('no user-scoped snapshot');
    expect(page).toContain('href={`#${botAnchor(bot)}`}');
    expect(page).toContain('Jump to bot card');
    expect(page).toContain('id={botAnchor(bot)}');
    expect(page).toContain('href: `#${botAnchor(bot)}-settings`');
    expect(page).toContain('href: `#${botAnchor(bot)}-statistics`');
    expect(page).toContain('href: `#${botAnchor(bot)}-warnings`');
    expect(page).toContain('href: `#${botAnchor(bot)}-runtime-evidence`');
    expect(page).toContain('id={`${botAnchor(bot)}-settings`}');
    expect(page).toContain('id={`${botAnchor(bot)}-statistics`}');
    expect(page).toContain('id={`${botAnchor(bot)}-runtime`}');
    expect(page).toContain('id={`${botAnchor(bot)}-runtime-evidence`}');
    expect(page).toContain('scrollMarginTop: 90');
    expect(page).not.toContain('schema.');
    expect(page).not.toContain('getBotAdapter');
    expect(page).not.toContain('exchangeApiKeySecrets');
    expect(page).not.toContain('rawJson');
    expect(page).not.toContain('botConfigVersions');
    expect(page).not.toContain('adminSaveBotGlobalConfigAction');
    expect(page).not.toContain('saveBotConfigAction');
    expect(page).not.toContain('CsrfField');
    expect(page).not.toContain('type="submit"');
    expect(page).not.toContain('startBot');
    expect(page).not.toContain('stopBot');
    expect(page).not.toContain('applyConfigAction');
    expect(page).not.toMatch(/applyConfig\(/);
  });

  it('maps and disables Legacy provider accounts through CSRF/admin/Zod/audited DB actions only', () => {
    const schemas = read('apps/web/src/features/admin/schemas.ts');
    const actions = read('apps/web/src/features/admin/actions.ts');
    const mapAction = sourceForFunction(actions, 'adminMapLegacyProviderAccountAction');
    const disableAction = sourceForFunction(actions, 'adminDisableLegacyProviderAccountAction');

    expect(schemas).toContain('mapLegacyProviderAccountSchema');
    expect(schemas).toContain('disableLegacyProviderAccountSchema');
    expect(schemas).toContain('Provider account ID contains unsupported characters');
    expect(mapAction).toContain('requireUser');
    expect(mapAction).toContain('assertAdmin');
    expect(mapAction).toContain('assertCsrf');
    expect(mapAction).toContain('mapLegacyProviderAccountSchema.safeParse');
    expect(mapAction).toContain('ensureBotInstance');
    expect(mapAction).toContain('upsertBotProviderAccountMapping');
    expect(mapAction).toContain("productCode: 'legacy_bot'");
    expect(mapAction).toContain("provider: 'legacy-db'");
    expect(mapAction).toContain('reason: parsed.data.reason');
    expect(disableAction).toContain('disableLegacyProviderAccountSchema.safeParse');
    expect(disableAction).toContain('disableBotProviderAccountMapping');
    expect(disableAction).toContain('userId: parsed.data.userId');
    expect(disableAction).toContain("productCode: 'legacy_bot'");
    expect(disableAction).toContain("provider: 'legacy-db'");
    expect(disableAction).toContain('reason: parsed.data.reason');
    expect(actions).not.toContain('startBot');
    expect(actions).not.toContain('stopBot');
    expect(actions).not.toContain('applyConfig');
  });

  it('links the user directory to the read-only bot detail page', () => {
    const page = read('apps/web/src/app/admin/users/page.tsx');

    expect(page).toContain("from 'next/link'");
    expect(page).toContain('/admin/users/${u.id}/bots');
    expect(page).toContain('Read-only bot view');
    expect(page).toContain('bot details are read-only');
    expect(page).toContain('loadAdminBotHealth');
    expect(page).toContain('Bot owner selector');
    expect(page).toContain('buildBotOwnerSelectorRows');
    expect(page).toContain('normalizedQuery(firstParam(sp.q))');
    expect(page).toContain('email, name, user id, masked pub_id');
    expect(page).toContain('Tortila owners:');
    expect(page).toContain('Legacy mapped:');
    expect(page).toContain('Unmapped pub_id:');
    expect(page).toContain('Selected-user inspection only');
    expect(page).toContain('Results open read-only user settings and statistics');
    expect(page).toContain('System defaults live on Global defaults');
    expect(page).toContain('/admin/bots/config');
    expect(page).toContain('/admin/users/${snapshot.ownerUser.userId}/bots#bot-tortila_bot');
    expect(page).toContain('/admin/users/${mapped.userId}/bots#bot-legacy_bot');
    expect(page).toContain("action: mapped ? 'Open read-only Legacy view' : 'Open fleet diagnostics'");
    expect(page).toContain("href: mapped ? `/admin/users/${mapped.userId}/bots#bot-legacy_bot` : '/admin/bots'");
    expect(page).toContain('rowMatches(row, q)');
    expect(page).toContain('slice(0, 32)');
    expect(page).toContain('wtc-table-wrap');
    expect(page).not.toContain('providerAccountId');
    expect(page).not.toContain('apiSecret');
    expect(page).not.toContain('apiKey');
    expect(page).not.toContain('sealed');
    expect(page).not.toContain('rawJson');
    expect(page).not.toContain('startBot');
    expect(page).not.toContain('stopBot');
    expect(page).not.toMatch(/applyConfig\(/);
  });

  it('adds a read-only admin bot owner drilldown for mapped users and Legacy pub_id rows', () => {
    const page = read('apps/web/src/app/admin/bots/page.tsx');

    expect(page).toContain('botOwnerDrilldownRows');
    expect(page).toContain('Bot owner drilldown');
    expect(page).toContain('Read-only owner explorer');
    expect(page).toContain('Open read-only user view');
    expect(page).not.toContain('Open details');
    expect(page).toContain('/admin/users/${mappedUser.userId}/bots#${row.detailAnchor}');
    expect(page).toContain("detailAnchor: 'bot-tortila_bot'");
    expect(page).toContain("detailAnchor: 'bot-legacy_bot'");
    expect(page).toContain('pub_id ${account.pubId}');
    expect(page).toContain('mapping required');
    expect(page).toContain('fleet diagnostics only');
    expect(page).toContain('Tortila owner snapshots');
    expect(page).toContain('Legacy pub_id rows');
    expect(page).toContain('this page does not edit user settings, provider mappings, exchange keys, or live bot state');
    expect(page).not.toContain('adminMapLegacyProviderAccountAction');
    expect(page).not.toContain('adminDisableLegacyProviderAccountAction');
    expect(page).not.toContain('Map Legacy pub_id');
    expect(page).not.toContain('CsrfField');
    expect(page).not.toContain('type="submit"');
    expect(page).not.toContain('startBot');
    expect(page).not.toContain('stopBot');
    expect(page).not.toContain('applyConfigAction');
    expect(page).not.toMatch(/applyConfig\(/);
  });
});
